FROM python:3.12-slim

WORKDIR /app

RUN pip install --no-cache-dir --upgrade pip

RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu

COPY requirements.txt .

RUN pip install --no-cache-dir --timeout 120 --retries 10 -r requirements.txt

COPY . . 

EXPOSE 8501

CMD ["streamlit", "run", "app.py"]